# Generated by Django 3.0b1 on 2019-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentEmployee',
            fields=[
                ('GovernmentEmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('GovernmentEmployeeName', models.CharField(max_length=100)),
                ('GovernmentEmployeeAddress', models.TextField()),
                ('GovernmentEmployeePhnNumber', models.CharField(max_length=15)),
                ('GovernmentEmployeeGmail', models.EmailField(max_length=254)),
                ('GovernmentEmployeeDesignation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'govermentemployee',
            },
        ),
    ]
